- name: DataDog monitoring system
  hosts: webservers
  become: true
  tasks:
    - name: Install datadog agent
      ansible.builtin.import_role:
        name: datadog.dd.agent
      vars:
        datadog_api_key: '{{ dd_api_key }}'
        datadog_site: '{{ dd_site }}'
        datadog_checks:
          http_check:
            instances:
              - name: app
                url: '{{ app_host }}'
